app = "fly-vpn-app"  # Isko deploy ke time Fly.io replace karega
primary_region = "sin"

[build]

[env]

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443
